#
# Generated by generate_plugin.py.
#
# init.tmux: called by plugin.sh.tmux to initialize the plugin.
#

display -p '[tmux-which-key] Loading plugin ...'

#
# User options
#

set -g @wk_cfg_key_prefix_table "Space"
set -g @wk_cfg_title_style "align=centre,bold"
set -g @wk_cfg_title_prefix "tmux"
set -g @wk_cfg_title_prefix_style "fg=green,align=centre,bold"
set -g @wk_cfg_pos_x "R"
set -g @wk_cfg_pos_y "P"

#
# Custom variables
#

setenv -h log_info "#[fg=green,italics] [info]#[default]#[italics]"

#
# Menus
#

set -g @wk_menu_layout \
'Next "l" "nextl ; show-wk-menu #{@wk_menu_layout}" \
Tiled "t" "selectnl tiled" \
Horizontal "h" "selectl even-horizontal" \
Vertical "v" "selectl even-vertical" \
"Horizontal main" "H" "selectl main-horizontal" \
"Vertical main" "V" "selectl main-vertical"'

set -g @wk_menu_windows \
'"Window 1" "1" "select-window -t :1" \
"Window 2" "2" "select-window -t :2" \
"Window 3" "3" "select-window -t :3" \
"Window 4" "4" "select-window -t :4" \
"Window 5" "5" "select-window -t :5" \
"Window 6" "6" "select-window -t :6" \
"Window 7" "7" "select-window -t :7" \
"Window 8" "8" "select-window -t :8" \
"Window 9" "9" "select-window -t :9" \
"" \
Last "tab" last-window \
Choose "w" "choose-tree -Zw" \
Previous "p" previous-window \
Next "n" next-window \
New "c" "neww -c #{pane_current_path}" \
"" \
"+Layout" "l" "show-wk-menu #{@wk_menu_layout}" \
Rotate "o" "rotatew ; show-wk-menu #{@wk_menu_windows}" \
"Rotate reverse" "O" "rotatew -D ; show-wk-menu #{@wk_menu_windows}" \
"" \
Rename "R" "command-prompt -I \"#W\" \"renamew -- \\"%%\\"\"" \
Kill "x" killw'

set -g @wk_menu_resize \
'Left "h" "resizep -L ; show-wk-menu #{@wk_menu_resize}" \
Down "j" "resizep -D ; show-wk-menu #{@wk_menu_resize}" \
Up "k" "resizep -U ; show-wk-menu #{@wk_menu_resize}" \
Right "l" "resizep -R ; show-wk-menu #{@wk_menu_resize}" \
"Left more" "H" "resizep -L 10 ; show-wk-menu #{@wk_menu_resize}" \
"Down more" "J" "resizep -D 10 ; show-wk-menu #{@wk_menu_resize}" \
"Up more" "K" "resizep -U 10 ; show-wk-menu #{@wk_menu_resize}" \
"Right more" "L" "resizep -R 10 ; show-wk-menu #{@wk_menu_resize}"'

set -g @wk_menu_panes \
'Last "a" lastp \
Choose "p" "displayp -d 0" \
"" \
Left "h" "selectp -L" \
Down "j" "selectp -D" \
Up "k" "selectp -U" \
Right "l" "selectp -R" \
"" \
Zoom "z" "resizep -Z" \
"+Resize" "r" "show-wk-menu #{@wk_menu_resize}" \
"Swap left" "H" "swapp -t \"{left-of}\"" \
"Swap down" "J" "swapp -t \"{down-of}\"" \
"Swap up" "K" "swapp -t \"{up-of}\"" \
"Swap right" "L" "swapp -t \"{right-of}\"" \
Break "!" break-pane \
"" \
Mark "m" "selectp -m" \
Unmark "M" "selectp -M" \
Capture "C" capture-pane \
"Respawn pane" "R" restart-pane \
Kill "x" killp'

set -g @wk_menu_terminals \
'"Attached Opencode" "a" "run-shell \"~/dotfiles/scripts/tmux/toggle-opencode-attached.sh\"" \
Opencode "o" "run-shell \"~/dotfiles/scripts/tmux/toggle-opencode.sh\"" \
"Split horizontal" "|" "run-shell \"~/dotfiles/scripts/tmux/toggle-horizontal.sh\"" \
"Split vertical" "-" "run-shell \"~/dotfiles/scripts/tmux/toggle-vertical.sh 30\""'

set -g @wk_menu_buffers \
'Choose "b" "choose-buffer -Z" \
List "l" lsb \
Paste "p" pasteb'

set -g @wk_menu_sessions \
'Choose "s" "choose-tree -Zs" \
"List Sessions" "l" "run-shell \"~/dotfiles/scripts/tmux-sesh.sh\"" \
New "c" new \
Rename "r" rename'

set -g @wk_menu_plugins \
'Install "i" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/install_plugins" \
Update "u" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/update_plugins" \
Clean "c" "run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/clean_plugins"'

set -g @wk_menu_client \
'Choose "c" "choose-client -Z" \
Last "l" "switchc -l" \
Previous "p" "switchc -p" \
Next "n" "switchc -n" \
"" \
Refresh "R" refresh \
"+Plugins" "P" "show-wk-menu #{@wk_menu_plugins}" \
Detach "D" detach \
Suspend "Z" suspendc \
"" \
"Reload config" "r" reload-config \
Customize "," "customize-mode -Z"'

set -g @wk_menu_root \
'"Command Prompt" "space" command-prompt \
Refresh "r" "source-file ~/dotfiles/.tmux.conf \; display \"Reloaded!\"" \
"last window" "tab" last-window \
"Copy mode" "v" copy-mode \
"" \
"Window 1" "1" "select-window -t :1" \
"Window 2" "2" "select-window -t :2" \
"Window 3" "3" "select-window -t :3" \
"Window 4" "4" "select-window -t :4" \
"Window 5" "5" "select-window -t :5" \
"Window 6" "6" "select-window -t :6" \
"Window 7" "7" "select-window -t :7" \
"Window 8" "8" "select-window -t :8" \
"Window 9" "9" "select-window -t :9" \
"List Windows" "l" "run-shell \"~/dotfiles/scripts/tmux-switch-or-create-pane.sh\"" \
"" \
"+Windows" "w" "show-wk-menu #{@wk_menu_windows}" \
"+Panes" "p" "show-wk-menu #{@wk_menu_panes}" \
"+Terminals" "t" "show-wk-menu #{@wk_menu_terminals}" \
"+Buffers" "b" "show-wk-menu #{@wk_menu_buffers}" \
"+Sessions" "s" "show-wk-menu #{@wk_menu_sessions}" \
"+Client" "C" "show-wk-menu #{@wk_menu_client}" \
"" \
Time "T" clock-mode \
"Show messages" "\~" show-messages \
"+Keys" "?" "list-keys -N"'

#
# Macros
#

set -gF @wk_cmd_show \
"display-menu \
-x '#{@wk_cfg_pos_x}' \
-y '#{@wk_cfg_pos_y}' \
-T '#[#{@wk_cfg_title_style}]#[#{@wk_cfg_title_prefix_style}]#{@wk_cfg_title_prefix}#[#{@wk_cfg_title_style}]'"

set -gF command-alias[200] show-wk-menu=\
'#{@wk_cmd_show}'

set -gF command-alias[201] show-wk-menu-root=\
'#{@wk_cmd_show} #{@wk_menu_root}'

set -gF command-alias[202] reload-config=\
'display "#{log_info} Loading config... " ; \
source-file $HOME/.tmux.conf ; \
display -p "\n\n... Press ENTER to continue"'

set -gF command-alias[203] restart-pane=\
'display "#{log_info} Restarting pane" ; \
respawnp -k -c #{pane_current_path}'

#
# Keybindings
#

display -p "[tmux-which-key] Binding prefix table key to #{@wk_cfg_key_prefix_table} ..."
run-shell "tmux bind-key -Tprefix #{@wk_cfg_key_prefix_table} show-wk-menu-root"

display -p '[tmux-which-key] Done'
